spring:
  autoconfigure:
      exclude:
        - org.apache.activemq.ActiveMQConnectionFactory
        - org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory
        - org.springframework.data.cassandra.core.CassandraAdminOperations
        - org.springframework.data.cassandra.repository.CassandraRepository


logging:
  level.: info