spring:
  autoconfigure:
      exclude:
        - org.apache.activemq.ActiveMQConnectionFactory
        - org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory
        - org.springframework.data.cassandra.core.CassandraAdminOperations
        - org.springframework.data.cassandra.repository.CassandraRepository

  data:
      mongodb:
          host: 10.60.16.81
          port: 27017
          database: horizon-claim-db

logging:
  level.: info